/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.vistas;

import com.unab.edu.DAO.clsUsuario;
import com.unab.edu.dao.clscuentausuario;
import com.unab.edu.entidades.cuentasUsuario;
import com.unab.edu.entidades.usuario;
import java.sql.Date;
import java.util.Set;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author landa
 */
public class Usuario extends javax.swing.JFrame {

    double Saldo = 0;
    usuario user;
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        user=Loguin.usu;
        lblWelcome.setText(user.getUsuario());
        MostrarTransaccion();
        setLocationRelativeTo(this);
        
    }
    void MostrarTransaccion() {
        String TITULOS[] = {"SALDO", "TRANSACCIÓN", "FECHA"};
        DefaultTableModel modeloTabla = new DefaultTableModel(null, TITULOS);
        clscuentausuario transaccion = new clscuentausuario();
        var listado = transaccion.Transacciones(user);
        String filas[] = new String[3];
        double abonos = 0;
        double cargos = 0;
        for (var iterarDatos : listado) {
            filas[0] = String.valueOf(iterarDatos.getSaldo());
            if (iterarDatos.getTransaccion() == 1) {
                filas[1] = "Abono";
                abonos += iterarDatos.getSaldo();
            } else {
                filas[1] = "Cargo";
                cargos += iterarDatos.getSaldo();
            }
            filas[2] = String.valueOf(iterarDatos.getFecha());
            //Agregar a la fila
            modeloTabla.addRow(filas);
        }
        Saldo = abonos - cargos;
        tblUsuario.setModel(modeloTabla);
        lblDisponible.setText(String.valueOf(Saldo));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBienvenida = new javax.swing.JLabel();
        lblBienvenida1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRetiro = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        txtRetiro = new javax.swing.JTextField();
        lbl$ = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblBienvenida2 = new javax.swing.JLabel();
        lblDisponible = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblBienvenida.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBienvenida.setText("BANCO CENTRAL SALVADOREÑO");

        lblBienvenida1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBienvenida1.setText("BANCO CENTRAL SALVADOREÑO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlShadow);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-money.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblRetiro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblRetiro.setText("Cantidad A Retirar");

        btnRetirar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRetirar.setText("RETIRAR");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        txtRetiro.setFont(new java.awt.Font("Yu Gothic Medium", 2, 10)); // NOI18N

        lbl$.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl$.setText("$");

        lblSaldo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSaldo.setText("Saldo : $ ");

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsuario);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel2.setText("ESTADO DE CUENTA");

        lblBienvenida2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblBienvenida2.setText("BANCO CENTRAL SALVADOREÑO");

        lblDisponible.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDisponible.setText(".");

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblWelcome.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl$, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBienvenida2)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRetiro)
                            .addComponent(lbl$)
                            .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo)
                            .addComponent(lblDisponible))
                        .addGap(18, 18, 18)
                        .addComponent(btnRetirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWelcome))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed

    boolean Numero;
        double Retiro = 0;
        clscuentausuario transacciones = new clscuentausuario();
        cuentasUsuario transaccion = new cuentasUsuario();
        try {
            Retiro = Double.parseDouble(txtRetiro.getText());
            Numero = true;
        } catch (Exception e) {
            Numero = false;
        }
        Date dte = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        transaccion.setFecha(dte);
        //Primera implementacion de Fecha
//        System.out.println(formato.format(date));
        //Validar si lo ingresado son numeros
        if (txtRetiro.getText() != "" && Retiro != 0) {
            //Validar que sea divisible entre 5
            if (Retiro % 5 == 0) {
                //validad si tiene saldo disponible
                if (Retiro <= Saldo) {
                    transaccion.setSaldo(Retiro);
                    transaccion.setIdUsuario(user.getIdUsuario());
                    transaccion.setTransaccion(2);
                    transacciones.agregarTransaccion(transaccion);
                    MostrarTransaccion();
                    txtRetiro.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede retirar más");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Solo se permiten cantidades divisibles entre 5");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese cantidades válidas");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl$;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblBienvenida1;
    private javax.swing.JLabel lblBienvenida2;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtRetiro;
    // End of variables declaration//GEN-END:variables

    
}
